POST http://localhost:3019/api/greet
content-type: application/json

//{
    //"language" : "xhosa",
    //"greeting" : "Molo"
//}

### 

GET https://creating-api.onrender.com/api/greet?name=Andrey&language=xhosa
content-type: application/json

{
    "language" : "xhosa",
    "greeting" : "Molo"
}